[package]
name = "tic-tac-toe-rust"
version = "0.1.0"
authors = ["Abhishek Sriram <68271853+Noobsiecoder@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"